### ISSUE TITLE
Multichannel files not compatible with apply_filter option

### ISSUE THREAD

**Issue by megies** [barsch/seishub.plugins.seismology#4]

**Comment by megies** [comment]
- MSEED files and apply_filter=True: cannot work IMHO because the mapped ID from the DB results is used with "sourcename" option. This tries to select channels in readMSEED that are not in the file (because in the file there are the unmapped, original channels). The problem is here already: https://github.com/barsch/seishub.plugins.seismology/blob/master/seishub/plugins/seismology/waveform.py#L379
  In this case currently nothing will be returned because readMSEED can not find the appropriate channels.
- other file types: same problem, the selection cannot succeed, but the problem comes later and is temporarily fixed by putting the (useless!?) selection after the mapping. This poses a problem only for multichannel files (all channels get mapped) https://github.com/barsch/seishub.plugins.seismology/blob/master/seishub/plugins/seismology/waveform.py#L396

I am not sure if this can be fixed at all, since the mapping is done at indexing time and not available at request time.

**Comment by krischer** [comment]
What is `apply_filter` supposed to do?

**Comment by megies** [comment]
When providing a mapping file for obspy-indexer at index time, it indexes the trace not with the seed id as in the waveform file but with the seed id defined in the mapping file. At the same time the original file stays unchanged. "apply_filter=True" then simply applies the seed id as it is indexed in the DB to all traces in the read in Stream. The database itself is not aware of any mapping that might have been applied during indexing. Therefore we had a problem earlier with the restricting the result to one channel (to correctly support multichannel files), because the channel we use for the "stream.select()" (from the DB) might not be the same channel as in the file (prior to mapping). So, with multichannel files this can not work..

The obvious solution would be to move the mapping to SeisHub and handle it there, instead of using it during indexing with no means to trace it back. No idea how complicated that would be and maybe it is just not worth it. I guess, the question is if we really want support for multichannel files that bad.

**Comment by krischer** [comment]
Wow. I was not aware of that but I do think we should support multichannel files. What is the mapping used for in the first place?

I guess the best solution would be do to the mapping at request time. Let the indexer index whatever is written in the files. At request time and mapping are resolved and the correct data is returned. Should be fairly simple - the mappings could be specified as a configuration value. Only the waveform mapper get's slightly more complex but that is acceptable in my opinion. Let's attempt it next week. Cheers!

**Comment by megies** [comment]
I agree, the mapping should definitively take place at request time.

The mapping was implemented because sometimes in temporary station setups a digitizer specific seed id is written instead of the real station description seed id. The mapping avoids touching and modifying the original data written by the digitizer, which is always highly unwanted.

**Comment by megies** [comment]
One problem could be the Client methods that return station lists. I don't know how these are implemented right now but they might have to be adapted if the mapping is done at request time.

**Comment by megies** [comment]
Since this has popped up with problems once again..

Core of the problem: Both the indexer _and_ the seishub server have to be aware of the mapping. The indexer because it inserts the mapped values in the db, the seishub server because it needs to understand which original channels should be read from file when a mapped db channel entry is requested.

Ideally the indexer should store the performed mapping in the db (new table for mappings? new column for channels in current table setup?). This would have the disadvantage that a reindexing of existing dbs might likely be necessary.
Another (simpler) option is to store a path to a local file with the mapping (used for the indexing) in seishub. This would have the disadvantage that if the mapping file is changed at some point it does not necessarily represent the mapping as applied by the indexer anymore.

Opininons, @krischer, @barsch?

**Comment by barsch** [comment]
wontfix
